### ISSUE TITLE
Hacktoberfest label missing

### ISSUE THREAD

**Issue by TheoGimenez7** [Aayushi-Mittal/Gamers-Console#12]
## Description
You forgot to add the hacktoberfest-accepted label.

### Detailed Bug Report
This year, hacktober needs a new label called hacktoberfest-accepted.

Here is the webpage where it's described : 
https://hacktoberfest.digitalocean.com/hacktoberfest-update

Here is a link to the specific solution : 
https://hacktoberfest-assets.nyc3.cdn.digitaloceanspaces.com/hacktoberfest-label-add-gif-min.gif

Thanks and good hacktoberfest !

**Comment by Aayushi-Mittal** [comment]
```
To put the rules in a form consistent with the spirit of Hacktoberfest:

PRs count if:
Submitted during the month of October AND
Submitted in a public repo AND (
  The PR is labelled as hacktoberfest-accepted by a maintainer OR
  Submitted in a repo with the hacktoberfest topic AND (
    The PR is merged OR
    The PR has been approved
  )
)
```
**To be more concise :** PR will be counted if submitted in the month of October in a public repo 
`hacktoberfest-accepted label || (hacktoberfest topic && (merged || approved) )`

- I have added the topic hacktoberfest to my repository.
- I am merging as well as approving the pull requests.

So, Don't worry it will be counted towards [Hacktoberfest](https://hacktoberfest.digitalocean.com/hacktoberfest-update).

But Still I will add the `hacktoberfest-accepted` label to avoid the confusion.

**Comment by Aayushi-Mittal** [comment]
@TheoGimenez7 I hope the issue is resolved now.

**Comment by TheoGimenez7** [comment]
Oh ok ! Thanks for the precision :)
